###

GET http://localhost:8080/admin/order?page=0&size=10
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NSwicm9sZSI6WyJzdXBlcl9hZG1pbiJdLCJlbWFpbCI6InB0ZHVuZzI2MDAwQGdtYWlsLmNvbSIsInN0YXR1cyI6IkFDVElWRSIsImF1dGhlbnRpY2F0aW9uT2JqZWN0IjoiVXNlciIsImlhdCI6MTcxNjU2MDM3MiwiZXhwIjoxNzE3NDI0MzcyfQ.m2J7zYErBzTi7GkOoOY4-_SvfJxW5CFKE-NZZxuHVyK3O-5YyJfu6IUw1-03ZM6pIY13UMMoAenbwryBxRWoyQ


###
PUT http://localhost:8080/admin/employee/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6NSwicm9sZSI6WyJzdXBlcl9hZG1pbiJdLCJlbWFpbCI6InB0ZHVuZzI2MDAwQGdtYWlsLmNvbSIsInN0YXR1cyI6IkFDVElWRSIsImF1dGhlbnRpY2F0aW9uT2JqZWN0IjoiVXNlciIsImlhdCI6MTcxNjU2MDM3MiwiZXhwIjoxNzE3NDI0MzcyfQ.m2J7zYErBzTi7GkOoOY4-_SvfJxW5CFKE-NZZxuHVyK3O-5YyJfu6IUw1-03ZM6pIY13UMMoAenbwryBxRWoyQ
Content-Type: application/json

{"name":"John Doe","phone":"1234567890","address":"123 Main Streettt","email":"john.doe@example.com"}