### create order
POST {{host}}/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    {
      "name": "DELL Vostro 5010",
      "price": 15000000,
      "weight": 1.3,
      "itemCategory": "HIGH_VALUE",
      "quantity": 1
    },
    {
      "name": "Bộ dụng cụ vệ sinh laptop",
      "price": 29990,
      "weight": 0.3,
      "itemCategory": "FRAGILE",
      "quantity": 2
    }
  ],
  "deliveryType": "FAST",
  "note": "Giao nhanh nhanh tí có việc",
  "paidType": "SENDER",
  "status": "DRAFT",
  "sender_object_id": 0,
  "receiver_object_id": 0
}

{
  "items": [
    {
      "name": "Thức ăn cho mèo",
      "price": 536000,
      "weight": 5,
      "itemCategory": "BLOCK",
      "quantity": 3
    },
    {
      "name": "Ghế ngồi dành cho mèo",
      "price": 59990,
      "weight": 1.5,
      "itemCategory": "FRAGILE",
      "quantity": 2
    },
    {
      "name": "Bộ dụng cụ đồ ăn dành cho thú cưng",
      "price": 99900,
      "weight": 0.3,
      "itemCategory": "HIGH_VALUE",
      "quantity": 2
    }
  ],
  "deliveryType": "NORMAL",
  "note": "Lấy loại hải sản, còn bộ dụng cụ lấy loại decord hình mèo mình",
  "paidType": "SENDER",
  "status": "DRAFT",
  "sender_object_id": 0,
  "receiver_object_id": 0
}