### create order
POST {{host}}/order
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 0,
  "deliveryType": "NORMAL",
  "note": "abcd",
  "paidType": "SENDER",
  "status": "CREATED",
  "senderObjectId": 25,
  "receiverObjectId": 26,
  "items": [
    {
      "id": 0,
      "name": "must have",
      "itemCategory": "FRAGILE",
      "quantity": 1,
      "weight": 1000,
      "price": 10000
    }
  ]
}