### create order
POST {{host}}/transfer-object
Authorization: Bearer {{token}}
Content-Type: application/json

# sender
{
  "id": 0,
  "atOfficeFlg": true,
  "receiveShift": "AFTERNOON",
  "customerId": 1,
  "postOfficeId": nul,
  "actionDate": "2024-05-26T00:00:00+07:00"
}
